---
title: "assignment"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
data taken from site:- [link](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip)

## read and process the data

```{r results="hide"}
activity<-read.csv("activity.csv")
library("ggplot2")
recorded<-subset(activity,!is.na(activity$steps))
```

no of steps recorded each day

```{r}
g<-ggplot(data=recorded,aes(date,steps))+ geom_histogram(stat="identity")
g+theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## mean and median steps per day
```{r}
mean_per_day<-tapply(recorded$steps,recorded$date,mean)
mean_per_day<-mean_per_day[!is.na(mean_per_day)]
mean_per_day
median_per_day<-tapply(recorded$steps,recorded$date,median)
median_per_day<-data.frame(median_per_day)
median_per_day
```

time series plot

```{r}
plot(unique(recorded$date), mean_per_day,pch=20)
lines(unique(recorded$date), mean_per_day)
```

## Max average

the interval that contains highest avg no of steps.

```{r}
steps_interval<-tapply(recorded$steps,recorded$interval,mean)
max<-steps_interval[steps_interval==max(steps_interval)]
max
```

## Imputing Data
replace na by mean of that particular interval 
```{r}
sum(is.na(activity$steps))
activity2<-activity
activity2[is.na(activity2$steps),"steps"]<-steps_interval[as.character(activity2[is.na(activity2$steps),"interval"])]
```

new mean and median per day
```{r}
mean_per_day<-tapply(activity2$steps,activity2$date,mean)
mean_per_day<-data.frame(mean_per_day)
mean_per_day
median_per_day<-tapply(activity2$steps,activity2$date,median)
median_per_day<-data.frame(median_per_day)
median_per_day
```

## Recalculating steps per day histogram

```{r}
g<-ggplot(data=activity2,aes(date,steps))+ geom_histogram(stat="identity")
g+theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

weekdays vs weekends

```{r}
recorded["days"]<-weekdays(as.Date(recorded$date,"%Y-%m-%d"))
recorded[grepl("Monday|Tuesday|Wednesday|Thursday|Friday",recorded$days),"weekends"]<-"weekday"
recorded[grepl("Saturday|Sunday",recorded$days),"weekends"]<-"weekend"
recorded[,"weekends"]<-as.factor(recorded$weekends)
ggplot(data=recorded,aes(interval,steps))+geom_line()+facet_grid(.~weekends)
```
  

